disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - trailing_whitespace
  - todo
  - function_body_length
  - inclusive_language
  - cyclomatic_complexity
  - comment_spacing
  - orphaned_doc_comment
  - mark
  - vertical_whitespace
  - file_length

opt_in_rules: # some rules are only opt-in
  - unused_import
  - closure_spacing
  - anyobject_protocol
  - toggle_bool
  - strong_iboutlet
  - identical_operands
  - prefer_self_type_over_type_of_self
  - empty_collection_literal

  # Find all the available rules by running:
  # swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
  - ChatRoom

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/Libs
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

# Test.swift 結尾的檔案不做 force_unwrapping 的檢查
file_name_no_force_unwrapping:
  name_pattern: "^(?!.*Tests\\.swift)"
  nested_configs:
    - path: "."
      config:
        opt_in_rules:
          - force_unwrapping

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  warning: 250
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
# they can set both implicitly with an array
type_body_length:
  - 400 # warning
  - 500 # error
# # or they can set both explicitly
#file_length:
#  warning: 500
#  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
cyclomatic_complexity:
  ignores_case_statements: true
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
