-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1nz9woCVwMA2JVow
SwkuB3jzcE7cyZ9jGFLY5Gxj6pOgCgYIKoZIzj0DAQehRANCAASAvT/DmyQ4tHYa
Icheckq8ApgZSRFK+PjdNtHQPABN4nzmQt6Kax/YUh6JVjF+pScVNEzNRpQHdaNI
1lNUMHmH
-----END PRIVATE KEY-----